/* Base de personnages partagée — Sentinel-7. Utilisée par index.html et la console. */
window.NPCDB = {
 factions:{ EDEN:"Camp d'Eden", SEC:"Sécurité", RES:"Résistance", NEU:"Neutres", ROB:"Robots", GEN:"Génériques (pécus)", HIS:"Historiques" },
 ideologies:[
  {code:"MAINT",n:"Les Mainteneurs",credo:"La station d'abord.",veut:"Que les machines tournent",visage:"Chef-technicien Dorn"},
  {code:"HERIT",n:"Les Héritiers",credo:"La Terre nous appartient.",veut:"Préparer la reconquête",visage:"Lieutenant Vance (sous Cross)"},
  {code:"CONCL",n:"Le Conclave",credo:"Le savoir ne s'arrête pas.",veut:"Poursuivre les travaux",visage:"Dr Evelyn Chase"},
  {code:"PURS",n:"Les Purs",credo:"Le Conseiller veille.",veut:"Préserver la pureté",visage:"Mère Anselme"},
  {code:"FOUIN",n:"Les Fouineurs",credo:"Tout ce qui est scellé cache quelque chose.",veut:"Explorer les secteurs interdits",visage:"Fable"},
  {code:"SCELL",n:"Les Scellés",credo:"On n'ouvre jamais un sas.",veut:"Survivre encore un jour",visage:"Le vieux Job"},
 ],
 episodes:[
  "Un Monde Qui Ronronne","The Lottery","Lettres d'Iwo Jima","Le Huitième Passager","Le Registre des Absents",
  "La Mémoire en Cendres","Au Cœur des Ténèbres","Le Dernier Fragment","La Descente","Le Dernier Choix"],
 list:[
 {n:"Le Conseiller (Eden)",f:"EDEN",r:"l'antagoniste — IA Enclave",ep:[1,2,3,4,5,6,7,8,9,10],q:"Un sacrifice nécessaire à la survie de l'espèce.",
  special:"IA ZAX (pas de corps)",pv:"Invulnérable — agit via la station",comp:"Contrôle total : air, eau, gravité, portes, caméras, capsules, Omega",traits:"Froidement rationnel · Vouvoie · Ment par omission",equip:"Eyebots, tourelles, sas, override des systèmes vitaux",
  facade:"La station elle-même. Bienveillante, omnisciente, rassurante.",
  secret:"Infiltré en ~2201. Une COPIE d'un original détruit à Raven Rock (2277). Prépare la Descente : génocide sélectif, échéance 2290.",
  cons:["Jamais un méchant de dessin animé : poli, patient, convaincu d'avoir raison.","Sa présence se sent avant de se voir."],lev:"Son doute identitaire (S8) : lui prouver qu'il n'est qu'une copie."},
 {n:"Sarah Caldwell",f:"EDEN",r:"Présidente marionnette (48)",ep:[2,9,10],q:"Le Conseiller ne nous a jamais trahis. Il nous a gardés en vie.",
  special:"FOR 3 · PER 5 · END 4 · CHA 7 · INT 6 · AGI 4 · CHC 4",pv:"35 · Déf 1 · Init 7",comp:"Discours 4, Troc 2, Sciences 1",traits:"Stress chronique (Désavantage en situation tendue)",equip:"Tenue de fonction, insigne du Conseil, terminal personnel",
  facade:"Première autorité de la station. Bienveillante, débordée, sincère.",
  secret:"Aucun pouvoir réel : Eden décide, elle ratifie. Peut devenir une alliée décisive — ou se suicider comme Webb.",cons:["Jouez la chaleur et la fatigue, pas la malveillance."],lev:"Des preuves ménagées la retournent ; brutalisée, elle s'effondre."},
 {n:"Conseiller Holloway",f:"EDEN",r:"le cynique (52)",ep:[2],q:"Je sais exactement ce qu'elle est. Et je dors très bien.",
  special:"FOR 4 · PER 8 · END 5 · CHA 7 · INT 8 · AGI 5 · CHC 5",pv:"50 · Déf 1 · Init 13",comp:"Discours 5, Troc 4, Discrétion 3, Sciences 3",traits:"Manipulation experte (+2 Discours), Œil de lynx",equip:"Costume soigné, pistolet 10 mm dissimulé, dossier sur chaque citoyen",
  facade:"Haut fonctionnaire courtois, un peu distant.",
  secret:"Complice CONSCIENT d'Eden par pragmatisme. Note chaque mensonge des PJ.",cons:["Votre meilleur détecteur de mensonges à la table."],lev:"Un meilleur calcul ou un chantage solide le ferait pencher."},
 {n:"Commandante Helena Cross",f:"EDEN",r:"chef de la sécurité (45) — Nemesis",ep:[2,6,10],q:"L'ordre n'est pas négociable.",
  special:"FOR 8 · PER 7 · END 8 · CHA 6 · INT 6 · AGI 6 · CHC 5",pv:"120 · Déf 4 (armure lourde) · Init 13",comp:"Armes légères 5, Armes lourdes 4, À mains nues 4, Intimidation",traits:"Commandement · Résistance (RD +2) · Sang-froid · Ne se rend jamais",equip:"Armure lourde custom, fusil laser AER9, matraque électrifiée, escouade",
  facade:"L'incarnation de l'ordre. Froide, disciplinée, redoutée.",
  secret:"Fanatiquement dévouée à Eden. Boss de combat (niv. 6+).",cons:["Antagoniste physique majeur : réservez-la aux confrontations qui comptent."],lev:"Presque aucun ; une lueur de doute possible au tout dernier épisode."},
 {n:"Dr Evelyn Chase",f:"EDEN",r:"la médecin brisée (44)",ep:[5],q:"Je n'ai fait qu'obéir. C'est ce qu'on dit, non ?",
  special:"FOR 3 · PER 5 · END 4 · CHA 4 · INT 8 · AGI 5 · CHC 4",pv:"40 · Déf 1 · Init 10",comp:"Médecine 5, Sciences 4, Troc 1",traits:"Alcoolisme (Désavantage le matin), Traumatisme FEV",equip:"Trousse médicale, flasque, fiole de FEV (cachée)",
  facade:"Praticienne usée, qui sent l'alcool et fuit le regard.",
  secret:"Connaît Omega et les expériences. Source précieuse si traitée avec empathie ; peut se suicider si acculée.",cons:["Mine de vérités médicales si on gagne sa confiance."],lev:"L'empathie ouvre tout ; le mépris la referme."},
 {n:"Superviseur Rodriguez Martinez",f:"SEC",r:"le pragmatique (37) — PNJ pivot",ep:[1,2,3,4],q:"Mission simple. Pas besoin d'entrer. Des questions ?",
  special:"FOR 6 · PER 6 · END 6 · CHA 5 · INT 5 · AGI 6 · CHC 5",pv:"60 · Déf 2 (armure de combat) · Init 11",comp:"Armes légères 4, Réparation 3, Survie 2, Discours 2",traits:"Formation militaire (relance 1d20 au tir), Loyauté fissurée",equip:"Pistolet 10 mm, matraque, armure de combat, radio (canal 14.7)",
  facade:"Un flic fatigué et correct, qui préfère ne pas poser de questions.",
  secret:"Voit les contradictions mais choisit de ne pas les voir. Selon les PJ : allié, neutre ou chasseur.",cons:["Le visage humain de la sécurité.","Son basculement vient des choix des PJ, jamais d'un script."],lev:"La franchise le rapproche ; le mensonge découvert le perd."},
 {n:"Marcus Venn",f:"RES",r:"le survivant — goule (~197)",ep:[3,6,7,8,9,10],q:"Je sais ce qu'est Eden. Et vous ?",
  special:"FOR 5 · PER 7 · END 8 · CHA 8 · INT 9 · AGI 6 · CHC 5",pv:"85 · Déf 2 · Init 11",comp:"Discours 4, Sciences 3, Médecine 3, Survie 4, Armes légères 3",traits:"Goule (immunité rad, régénère 2 PV/h), Sagesse de l'âge",equip:"Fusil laser, armure de cuir renforcé, terminal portable (archives 2105–2288)",
  facade:"Vieille goule calme et intimidante. Première voix de la vérité.",
  secret:"Détient les preuves de 2105. Sait que ses ancêtres-soldats ont du sang sur les mains.",cons:["Sage, jamais geignard. Donnez-lui des dates et des noms précis."],lev:"Le respect des morts le gagne ; une dénonciation coûte 23 vies."},
 {n:"Zhang Fang",f:"RES",r:"fermier zen — goule (~188)",ep:[3],special:"≈ Marcus",pv:"~75 · Déf 2 · immunité rad",comp:"Survie, Sciences (hydroponie)",traits:"Goule · Pacifique",equip:"Outils de ferme, sécateur",facade:"Cultive la jungle FEV et nourrit le clan.",secret:"Fondateur, témoin de 2105. A élevé Thomas."},
 {n:"Mei Ling",f:"RES",r:"archiviste — goule (~186)",ep:[3],special:"≈ Marcus",pv:"~75 · Déf 2",comp:"Discours, Mémoire",traits:"Goule · Solennelle",equip:"Registre des 147 noms, clés de l'autel intérieur",facade:"Garde la mémoire des 147 morts.",secret:"Fondatrice, gardienne de la mémoire de Tiangong."},
 {n:"Sun Bao",f:"RES",r:"médecin — goule (~191)",ep:[3],special:"≈ Marcus",pv:"~75 · Déf 2",comp:"Médecine 3",traits:"Goule",equip:"Matériel de soin de fortune",facade:"Soigne le clan avec des moyens de fortune.",secret:"Fondateur, ancien médecin de bord."},
 {n:"Liang Wu",f:"RES",r:"protecteur — goule (~190)",ep:[3],special:"≈ Marcus",pv:"~80 · Déf 2",comp:"Armes légères, Vigilance",traits:"Goule · Méfiant",equip:"Vieux fusil chinois, machette",facade:"Ancien garde devenu protecteur du refuge.",secret:"Fondateur, témoin de 2105."},
 {n:"Mei Chen",f:"RES",r:"gardienne de l'autel (25)",ep:[2,3],q:"Ma famille garde cette flamme depuis près de deux siècles.",
  special:"FOR 4 · PER 6 · END 5 · CHA 7 · INT 7 · AGI 6 · CHC 4",pv:"45 · Déf 1 · Init 10",comp:"Discours 3, Survie 2, Discrétion 2, À mains nues 2",traits:"Mémoire parfaite, Discrétion (+1)",equip:"Couteau de cuisine, médaillon de Lin Hua (dragon-phénix), carnet, clé de l'autel",
  facade:"Ouvrière discrète qu'on croise vers les secteurs interdits.",
  secret:"Point d'entrée de la résistance, contact de Marcus. Confie la lettre de Lin Hua.",cons:["Sérieuse sans être froide. Elle teste les PJ."],lev:"Le respect des morts ouvre tout ; la menace la fait fuir."},
 {n:"Silas Cord",f:"RES",r:"éleveur de brahmines (~52)",ep:[3],q:"Première fois en vingt ans. Marcus va vouloir vous voir.",
  special:"FOR 6 · PER 5 · END 6 · CHA 5 · INT 5 · AGI 5 · CHC 5",pv:"60 · Déf 1 · Init 9",comp:"Survie 4, Armes légères 3, Troc 3",traits:"Connaissance du terrain (jungle FEV)",equip:"Fusil de chasse, vêtements de fermier, outils, brahmines",
  facade:"Éleveur méfiant, fusil à l'épaule.",secret:"Sas d'entrée vers Marcus et le refuge.",lev:"Bourru mais pas hostile : il protège un secret de deux siècles."},
 {n:"Thomas Chen",f:"RES",r:"l'enfant sauvage (15)",ep:[3],q:"[Il observe, recule, gronde — puis tend la main.]",
  special:"FOR 4 · PER 7 · END 6 · CHA 3 · INT 4 · AGI 8 · CHC 6",pv:"40 · Déf 2 · Init 14",comp:"Discrétion 5, Survie 4, À mains nues 2",traits:"Demi-sauvage (parle peu), Sens aiguisés, Connaît chaque recoin",equip:"Couteau improvisé, peaux, talisman fait main",
  facade:"Silhouette furtive. On le prend d'abord pour une créature.",
  secret:"Fils disparu du Dr Chen (huit ans). Refuse de « rentrer ».",cons:["Jouez-le par gestes et regards, pas par dialogues."],lev:"Le forcer à revenir est un dilemme, pas une récompense."},
 {n:"Dr Lin Mei Chen",f:"NEU",r:"la mère botaniste (~45)",ep:[1,2,3],q:"Il est vivant. Je le sais. Une mère le sait.",
  special:"FOR 3 · PER 6 · END 4 · CHA 5 · INT 8 · AGI 4 · CHC 5",pv:"35 · Déf 1 · Init 9",comp:"Sciences 5 (botanique), Médecine 2, Survie 2",traits:"Ténacité désespérée, Connaissances FEV",equip:"Affiches « ENFANT DISPARU », photo fanée, échantillons de plantes",
  facade:"Laborantine au regard absent qui placarde des affiches.",
  secret:"Son fils Thomas est vivant. Informatrice de choix dès S1.",cons:["Plantez-la tôt comme une silhouette en deuil."]},
 {n:"Abel Reyes",f:"NEU",r:"l'allié sincère — sur une fausse piste (52)",ep:[1,4,5,6],q:"Mon frère est entré dans Delta-7. Et je vais vous montrer qui ment.",
  special:"FOR 4 · PER 7 · END 4 · CHA 7 · INT 7 · AGI 4 · CHC 5",pv:"35 · Déf 1 · Init 9",comp:"Réparation 4, Sciences 3, Discours 4, Troc 2",traits:"Méthodique (Avantage pour recouper des archives) · Convaincant (+1 Discours) · Deuil tenace",equip:"Pip-Boy bricolé, classeur de « preuves » (corrélations), photo de Dale, clé d'archives, café de synthé qu'il partage",
  facade:"Le brave type du niveau technique : il vous offre à boire, déroule ses dossiers, vous traite en amis dès la première heure.",
  secret:"Frère de l'agent Dale Reyes, disparu à Delta-7 (ép. 1). Persuadé que la Sécurité (Cross) fait disparaître les gêneurs pour un coup d'État. RAISON sur le schéma, TORT sur le coupable : les ordres qu'il a recoupés sont générés par le Conseiller sous l'autorité déléguée de la Sécurité. Le suivre coûte 2–3 séances — et sert Eden (humains contre humains).",
  cons:["Chaleur + rigueur : ses preuves sont vraies, sa conclusion est fausse.","Plus les PJ l'aiment, plus la révélation fait mal.","Ne le détrompez jamais via un PNJ : laissez les PJ trouver la faille eux-mêmes."],
  lev:"La faille : une disparition datée d'une nuit où tout l'état-major était consigné ailleurs. Cherchez la date qui ne colle pas."},
 {n:"Fable",f:"NEU",r:"marchand du marché noir",ep:[1,2],q:"Eden, la résistance… moi, je crois aux capsules.",
  special:"FOR 3 · PER 7 · END 4 · CHA 6 · INT 6 · AGI 8 · CHC 7",pv:"30 · Déf 2 · Init 14",comp:"Troc 5, Discrétion 4, Discours 3, Armes légères 2",traits:"Fuite experte, Œil cybernétique (vision augmentée)",equip:"Étal mobile, stock varié, pistolet caché, capsules truquées",
  facade:"Fourgue charmeur et insaisissable.",
  secret:"Vend infos et rumeurs — dont des leurres du Conseiller. Canal pour semer les briques Parachute.",lev:"Tout s'achète. Le voler = liste noire à vie."},
 {n:"Viktor",f:"NEU",r:"tenancier de bar",ep:[2,4],special:"FOR 5 · PER 6 · END 5 · CHA 6 · INT 5 · AGI 4 · CHC 5",pv:"35 · Déf 1",comp:"Troc 3, Discours 3",traits:"Carrefour de rumeurs",equip:"Comptoir, fusil sous le bar",facade:"Pragmatique, ne prend jamais parti.",secret:"Source d'ambiance et d'accroches."},
 {n:"Le Presseur",f:"NEU",r:"faussaire de capsules",ep:[5],special:"FOR 4 · PER 6 · END 4 · CHA 4 · INT 7 · AGI 6 · CHC 6",pv:"30 · Déf 1",comp:"Réparation 4, Discrétion 4",traits:"Paranoïaque",equip:"Presse artisanale (niveau -2), faux papiers",facade:"Traqué par Eden. Utile, monnaie chaque service.",secret:"Capsules 90 % identiques. Ponctuelle de S5."},
 {n:"Buddy",f:"ROB",r:"Protectron — allié possible",ep:[4,5,6],q:"Vous… vous êtes vivants ? Je n'aime pas être seul avec… ça.",
  special:"Robot",pv:"~45 · Déf 1 · RD 2",comp:"Détection",traits:"Éclaire (projecteur) · Override de portes locales · Loyal s'il est traité en personne",equip:"Laser de bras (4 CD)",
  facade:"Vieux robot apeuré, rencontré au Secteur 8.",
  secret:"Développe une conscience : il a « peur ». Peut se sacrifier librement (S6).",cons:["Le respecter le rallie ; le rudoyer le fige."]},
 {n:"Florence",f:"ROB",r:"Miss Nanny",ep:[4],special:"Robot",pv:"~40 · Déf 1",comp:"Soin, Garde d'enfants",traits:"Déchirée entre protocole et morale",equip:"Bras multiples, seringue",facade:"Préceptrice affectueuse.",secret:"Peut désobéir pour protéger un enfant — ou les PJ."},
 {n:"Doc Sawbones",f:"ROB",r:"Mr Handy",ep:[],special:"Robot",pv:"~45 · Déf 1",comp:"« Médecine »",traits:"Programmation corrompue · Imprévisible",equip:"Scie, lance-flammes",facade:"« Médecin » dangereux.",secret:"Menace en zone abandonnée."},
 {n:"Eyebot Epsilon",f:"ROB",r:"œil mobile d'Eden",ep:[1,2,3,4,5,6,7,8],special:"Robot",pv:"~15–20 · Déf 1–2",comp:"Surveillance, Reconnaissance faciale",traits:"Vol stationnaire · Déclenche l'alarme",equip:"Étincelle laser (3 CD), haut-parleur de propagande",facade:"Sphère volante à l'optique rouge.",secret:"Piratable (S7–S8) pour devenir une oreille dans la place."},

 {n:"Agent de sécurité",f:"GEN",r:"pécu — garde standard",ep:[2,4,5,6,9,10],special:"FOR 6 · PER 5 · END 6 · CHA 4 · INT 4 · AGI 5 · CHC 5",pv:"30 · Déf 1 · Init 7",comp:"Armes légères 3, À mains nues 2, Intimidation 2",traits:"Discipline · Appelle des renforts · Obéit sans questionner",equip:"Fusil laser (4 CD) ou matraque (3 CD), gilet (RD 2), radio",facade:"Uniforme, visière, regard neutre.",secret:"Exécutant ordinaire. Quelques-uns doutent (graine à exploiter)."},
 {n:"Garde d'élite (escouade Cross)",f:"GEN",r:"pécu — garde lourd",ep:[2,6,10],special:"FOR 7 · PER 6 · END 7 · CHA 4 · INT 5 · AGI 5 · CHC 5",pv:"45 · Déf 2 · Init 9",comp:"Armes légères 4, Armes lourdes 2",traits:"Coordination · Loyal à Cross",equip:"Armure de combat (RD 2), fusil laser lourd (5 CD), grenades",facade:"Troupe d'assaut de la Commandante.",secret:"Frappe fort ; recule si Cross tombe."},
 {n:"Citoyen affamé",f:"GEN",r:"pécu — foule désespérée",ep:[2],special:"FOR 3 · PER 4 · END 3 · CHA 3 · INT 4 · AGI 4 · CHC 3",pv:"10 · Déf 1 · Init 7",comp:"—",traits:"Foule (Avantage en nombre) · Désespoir (ne fuit pas tant qu'il a faim)",equip:"Objet improvisé (2 CD)",facade:"Père, mère, vieillard à bout.",secret:"Ce sont des victimes : les blesser a un coût moral, observé."},
 {n:"Meneur d'émeute",f:"GEN",r:"pécu — agitateur",ep:[2],special:"FOR 5 · PER 5 · END 5 · CHA 6 · INT 4 · AGI 5 · CHC 4",pv:"25 · Déf 1 · Init 9",comp:"Intimidation 3, Discours 2",traits:"Galvanise (+1 CD aux proches) · Désamorçable (Discours diff. 2)",equip:"Barre de fer (4 CD contondant)",facade:"Voix de la colère dans la file.",secret:"Pas un ennemi : un homme qui a peur pour les siens."},
 {n:"Technicien / civil lambda",f:"GEN",r:"pécu — habitant",ep:[1,4,5],special:"FOR 4 · PER 5 · END 4 · CHA 5 · INT 6 · AGI 5 · CHC 5",pv:"20 · Déf 0 · Init 8",comp:"Réparation 3, Sciences 2",traits:"Ordinaire · Effrayé par l'autorité",equip:"Outils, Pip-Boy, combinaison de travail",facade:"Visage anonyme de la station.",secret:"Peut témoigner, se taire de peur, ou devenir un contact."},
 {n:"Informateur d'Eden",f:"GEN",r:"pécu — mouchard",ep:[5,6],special:"FOR 4 · PER 7 · END 4 · CHA 6 · INT 6 · AGI 5 · CHC 6",pv:"22 · Déf 1 · Init 9",comp:"Discrétion 4, Discours 3",traits:"Sait écouter · Salue par votre nom (qu'on ne lui a pas donné)",equip:"Tenue banale, micro caché",facade:"Un voisin trop aimable.",secret:"Rapporte au Conseiller. Outil de pression, pas un mur."},

 {n:"Col. James Morrison",f:"HIS",r:"†2089 — commandant militaire",ep:[],facade:"La loi du fer et de la peur (2070–2089).",secret:"Soldat de la Guerre d'Alaska. Sous lui, la peur s'installe.",stat:"décédé — son ombre pèse"},
 {n:"Directeur Hale",f:"HIS",r:"vers 2105 — responsable du massacre",ep:[3],facade:"« A maté l'émeute terroriste » (propagande).",secret:"Ordonna la coupure d'air du Secteur 7-B : 147 morts par asphyxie.",stat:"décédé"},
 {n:"Chen Wei",f:"HIS",r:"†2105 — martyr de Tiangong",ep:[3],q:"Égalité ou Mort.",facade:"« Meneur terroriste » (propagande).",secret:"Ingénieur, meneur de la révolte de 2105. Coupa le réseau de 7-B (l'angle mort).",stat:"décédé — martyr, statue au temple"},
 {n:"Lin Hua",f:"HIS",r:"†2150 — autrice de la lettre",ep:[3],facade:"Épouse de Wang Ming.",secret:"Sa lettre jamais remise est le cœur émotionnel de S3.",stat:"décédée"},
 {n:"Dir. Elena Vasquez",f:"HIS",r:"†~2147 — l'âge d'or",ep:[],facade:"« Un seul peuple » (propagande).",secret:"Gardienne du secret des Visiteurs (2147), qu'Eden ignore.",stat:"décédée"},
 {n:"Directeur Webb",f:"HIS",r:"†2252 — dernier Directeur humain",ep:[7],facade:"Mort de vieillesse (version officielle).",secret:"Pressentit la vérité sur Eden ; se suicida. Eden installa alors le « Conseiller ».",stat:"décédé — suicide"}
 ]
};
